#!/bin/bash

QEMU=$(which qemu-system-x86_64)
QEMU_IMG=$(which qemu-img)
OVMF=('/usr/share/ovmf/x64/OVMF.fd' '/usr/share/ovmf/OVMF.fd') 

# Host system specs
RAM=$(grep MemTotal /proc/meminfo | awk '{print int($2 /1000)}')
THREADS=$(lscpu | awk 'NR == 7 {print $4}')
CORES=$(lscpu | awk 'NR == 8 {print $4}')
SOCKETS=$(lscpu | awk 'NR == 9 {print $2}')
CPUS=$(($SOCKETS * $CORES * $THREADS))
SCREEN_RES=$(cat /sys/class/graphics/*/virtual_size | sed 's/,/x/')

# Defaults
DEFAULT_DISK_SIZE="10G"

# Flags
F_CREATE=0

# VM variables
declare -A VARS=( [ram]=${RAM}
                  [cpus]=$CPUS 
                  [sockets]=$SOCKETS
)

FLAGS=("-enable-kvm -sdl -cpu host -vga virtio") # Default flags, updated in start()

# Check qemu is installed
if [ -z $QEMU ] || [ -z $QEMU_IMG ]; then
    echo "ERROR: qemu is not installed"
    exit 1
fi

function usage() {
    echo "
Usage: easy-emu [options]

-create     | -c [vm name]     Create a new virtual machine 
-run        | -r [vm name]     Start an existing VM
-cpus       | -C [num cpus]    Specify number of cpus. Default is host max
-iso        | -i               Path to OS ISO image
-memory     | -m [RAM in MB]   Specify RAM amount. Default is host max
-size       | -s [Size]        Specify size of virtual disk. Must specify unit (M = megabyte G = gigabyte). Default is 10G              
-fullscreen | -f               Start in fullscreen. Ctrl-Alt-F to exit 
          "
    exit 0
}

# Show some basic system info for host
function host() {
    echo "
Host specifications
--------------------------
Sockets:          $SOCKETS
Cores per socket: $CORES    
Threads per core: $THREADS
Total CPUs:       $CPUS
RAM:              $RAM M
Resolution:       $SCREEN_RES
"
    exit 0
}

# Start qemu VM
function run_vm() {
    $QEMU ${@}
}

# Create a qcow2 virtual HDD
function create_disk() {
    if [ -z "${VARS[iso]}" ]; then
        echo "No ISO image supplied"
        exit 1
    fi 
    if [ -z "${VARS[size]}" ]; then
        qemu-img create -f qcow2 -o size=$DEFAULT_DISK_SIZE ${VARS[name]}
    else
        qemu-img create -f qcow2 -o size=${VARS[size]} ${VARS[name]}
    fi     
}


if [ $# -lt 1 ]; then
    usage
    exit 0
else
    while [ $# -gt 0 ]; do
        case $1 in
            --help | -help | -h)
                usage
            ;; 
            --host | -host)
                host
            ;;
            --run | -run | -r)
                if [ ! -e $2 ]; then
                    echo "VM not found"
                    exit 1
                fi
                VARS+=( [name]=$2 )
                shift; shift
            ;;
            --create | -create | -c)
                if [ -e $2 ]; then
                    echo "$2 already exists"
                    exit 1
                fi
                F_CREATE=1
                VARS+=( [name]=$2 )
                shift; shift
            ;;
            --fullscreen | -fullscreen | -f)
                FLAGS+=( "-full-screen" )
                shift
            ;;
            --iso | -iso | -i)
                if [ ! -e $2 ]; then  
                   echo "ISO not found" 
                   exit 1
                fi 
                VARS+=( [iso]=$2 )
                shift; shift
            ;;
            --memory | -memory | -m)
                VARS+=( [ram]=$2 )
                shift; shift
            ;;
            --sockets | -sockets | -S)
                VARS+=( [sockets]=$2 )
                shift; shift
            ;;
            --cpus | -cpus | -C)
                VARS+=( [cpus]=$2 )
                shift; shift
            ;;
            --size | -size | -s)
                VARS+=( [size]=$2 )
                shift; shift
            ;;
            --uefi | -uefi)
                for i in "${OVMF[@]}"; do
                    if [ -e $i ]; then
                        UEFI_IMG=$i
                    fi
                done
                if [ -z UEFI_IMG ]; then
                    echo "Unable to find OVMF. Is it installed?"
                    exit 1
                fi
                FLAGS+=( "-bios $UEFI_IMG" )
                shift
            ;;
            *)
                usage
            ;;
            -test)
                shift
            ;;
        esac
    done
fi

function start() {    
    
    if [ $F_CREATE -gt 0 ]; then
        create_disk
    fi

    FLAGS+=( "-name ${VARS[name]}" "-drive file=${VARS[name]}" "-m ${VARS[ram]}" "-smp sockets=${VARS[sockets]},cores=${VARS[cpus]}" )

    if [ -n "${VARS[iso]}" ]; then
        FLAGS+=( "-cdrom ${VARS[iso]}" )
    fi
    
    run_vm ${FLAGS[@]}
}

start 